### ISSUE TITLE
Markup highlight puts literal tag end sign instead of entity.

### ISSUE THREAD

**Issue by rafalwrzeszcz** [PrismJS/prism#1292] opened 2018-02-12 07:52 UTC
Using markup (eg. `xml`) language breaks document as it converts `&gt;` into literal `>` signs (leaves `&lt;`, `&amp;` and others alone).

An example:

```xml
<pre class="language-xml"><code>&lt;element&gt;&lt;![CDATA[
    &lt;foo&gt;
]]&gt;&lt;/element&gt;</code></pre>
```

Expected output would be to have just token `<span>` highlighting elements added. But instead this is the computed value:

```xml
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>element</span><span class="token punctuation">></span></span><span class="token cdata">&lt;![CDATA[
    &lt;foo>
]]></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>element</span><span class="token punctuation">></span></span>
```

Note the `<span class="token punctuation">></span>` instead of `<span class="token punctuation">&gt;</span>` everywhere (even within `CDATA` block).

**Comment by Golmote** [comment] 2018-02-12 23:01
Hi @rafalwrzeszcz. Thanks for reporting. I was unable to reproduce the issue, though. https://codepen.io/anon/pen/xYrXzz

**Comment by Golmote** [comment] 2018-04-05 17:10
Closing this issue, since it could not be reproduced.

**Closed by Golmote** 2018-04-05 17:10 UTC
