### ISSUE TITLE
Python highlight: Comment won't show up on a different line

### ISSUE THREAD

**Issue by sanjay51** [PrismJS/prism#1715] opened 2019-01-24 03:57 UTC
Hi, I'm using prism and I've this code:

```
<pre class="line-numbers">
<code class="language-python">
import tensorflow as tf

x = tf.Variable(3, "X");

# Say hello
y = tf.Variable(a, b);
</code>
</pre>
```

It renders like this:
```
import tensorflow as tf

x = tf.Variable(3,"X");# Say hello
y = tf.Variable(a, b);
```
As you can see, the comment shows up on the previous line. Can you please look into this once? Possibly it's a python language highlight problem.

Here is a screenshot (cropped):
<img width="618" alt="screen shot 2019-01-23 at 7 53 42 pm" src="https://user-images.githubusercontent.com/4214056/51653592-f5980d80-1f48-11e9-84df-e360d474a137.png">

Thank you.

**Comment by sanjay51** [comment] 2019-01-27 05:59
*It's probably not a bug with prism - here is how I fixed it*.
I'm developing wordpress gutenberg blocks where this is happening, and my hunch is that some preprocessing step (with gutenberg) is messing the content of "code" blocks.

Here is how I fixed it: I renamed "code" to "codex" in the html tag, prism JS, prism CSS, and now the problem is fixed.

Thanks for looking into it anyway.

**Comment by RunDevelopment** [comment] 2019-01-27 10:46
I'm going to close the issue then because the cause doesn't seem to be Prism.

**Closed by RunDevelopment** 2019-01-27 10:46 UTC
