### ISSUE TITLE
Yaml ignores first line of code blocks

### ISSUE THREAD

**Issue by larsks** [PrismJS/prism#942] opened 2016-04-29 14:58 UTC
If I have this:

````
<pre class="language-yaml"><code>somekey: somevalue
anotherkey: anothervalue</code></pre>
````

Then prism will only highlight the second line.  I can do this:

````
<pre class="language-yaml"><code>
somkey: somevalue
anotherkey: anothervalue
</code></pre>
````

...and now prism will correctly highlight all the code, but I have a blank line at the start of the block (which impacts display and layout, because I am trying to top-align the code blocks with documentation in a multi-column layout).

**Comment by zeitgeist87** [comment] 2016-04-29 15:24
I can reproduce this with the yaml language.  The problem seems to be, that the yaml language definition uses an elaborate lookbehind to determine if something is a key or not:

```js
'key': {
		pattern: /(\s*[:\-,[{\r\n?][ \t]*(![^\s]+)?[ \t]*)[^\r\n{[\]},#]+?(?=\s*:\s)/,
		lookbehind: true,
		alias: 'atrule'
	},
```
Basically any of these characters have to precede a keyword: `[:\-,[{\r\n?]`

This example works:

```html
<pre class="language-yaml"><code>---
somkey: somevalue
anotherkey: anothervalue
</code></pre>
```

Should we consider that a feature or a bug? I'm not sure...

**Comment by larsks** [comment] 2016-04-29 15:59
I'm pretty sure I would call it a bug.  Would the following pattern fix it?

    (\s*(^|[:\-,[{\r\n?])[ \t]*(![^\s]+)?[ \t]*)[^\r\n{[\]},#]+?(?=\s*:\s)

This looks for `^` (beginning of input) in addition to a newline or carriage return at the beginning of the pattern.

**Comment by Golmote** [comment] 2016-04-29 16:05
Duplicate of #649 no?

**Comment by larsks** [comment] 2016-04-29 16:07
That is the same issue, although the resolution suggested there (use `---`) is a non-starter, because I'm highlighting individual chunks of YAML from a larger document.  The pattern I suggested in my previous comments seems to resolve this completely for all of my inputs.

**Closed** 2016-04-29 18:50 UTC
