### ISSUE TITLE
Keep line numbers in place

### ISSUE THREAD

**Issue by worldsdream** [PrismJS/prism#2765] opened 2021-02-14 17:24 UTC
I don’t see it anywhere, but can we keep the line numbers in place? 

At the moment when I scroll horizontal, the line numbers on the left side go with it. 

Shouldn’t line numbers stay on the left?

**Comment by RunDevelopment** [comment] 2021-02-14 19:12
Duplicate of #2493.

It's intended or rather tolerated behavior. All potential solutions to making them sticky are rather complicated.

**Closed by RunDevelopment** 2021-02-14 19:12 UTC
