### ISSUE TITLE
SQL : operators have white background

### ISSUE THREAD

**Issue by ThomasKientz** [PrismJS/prism#3274] opened 2021-12-06 21:09 UTC
**Information**
- Language: SQL
- Plugins: none

**Description**
Operators have a white background. 

<img width="684" alt="Capture d’écran 2021-12-06 à 22 08 03" src="https://user-images.githubusercontent.com/10157845/144922879-b0e1bd05-db09-4168-83fa-a63aeb1b0389.png">

**Code snippet**

[Test page](https://prismjs.com/test.html#language=sql)

<details>
<summary>The code being highlighted incorrectly.</summary>

```
SELECT Customers.CustomerName, Orders.OrderID
FROM Customers
LEFT JOIN Orders ON Customers.CustomerID = Orders.CustomerID
ORDER BY Customers.CustomerName;```

</details>

**Comment by RunDevelopment** [comment] 2021-12-06 21:46
That not a bug. It's an [intentional part of the theme](https://github.com/PrismJS/prism/blob/b58cd7227fec6c7ce312d87d24919ec109a0b7fd/themes/prism.css#L110). 

Duplicate of #1347, #1691.

**Closed by RunDevelopment** 2021-12-06 21:46 UTC
