### ISSUE TITLE
problem with dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by lucasfernandodev** [PrismJS/prism#3041] opened 2021-08-18 09:38 UTC
**Information:**
- Prism version: [1.24.1]
- Plugins: [a list of plugins you are using or 'none']
- Environment: [React.js and next.js]

**Description**
I installed primsjs via yarn, and add it to my blog and it's working, the problem is that the message below appears:

Warning: Prop `dangerouslySetInnerHTML` did not match. Server: post...

**Example**

```tsx
import PostStyle from "./post-styles.module.css";
import styles from "./style.module.css";
import CardImage from "../../Molecules/CardImage";
import Prism from "prismjs";
import { useEffect } from "react";
type Props = {
  content: string;
  thumbnail: string;
  title: string;
};

const PostBody = ({ content, thumbnail, title }: Props) => {
  useEffect(() => {
    Prism.highlightAll()
  }, []);
  return (
    <>
      <CardImage src={thumbnail} alt={title} />
      <article className={styles.section__article}>
        <div
          className={`${PostStyle["post"]}`}
          dangerouslySetInnerHTML={{ __html: content }}
        />
      </article>
    </>
  );
};

export default PostBody;
```

**Comment by RunDevelopment** [comment] 2021-08-18 10:13
I don't see how the waring is related to Prism. Does the `content` contain HTML with a `<pre>` element?

**Comment by lucasfernandodev** [comment] 2021-08-18 10:21
The content includes the html of an entire post and inside that post has the 'pre' and the 'code'.

**Comment by lucasfernandodev** [comment] 2021-08-18 10:39
Full error message:

react-dom.development.js?61bb:67 Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "<p>As discussed in the <a href=\"https://mage-css.ghost.io/welcome/\">introduction</a> post, one of the best things about Ghost is just how much you can customize to turn your site into something unique. Everything about your layout and design can be changed, so you're not stuck with yet another clone of a social network profile.</p><p>How far you want to go with customization is completely up to you, there's no right or wrong approach! The majority of people use one of Ghost's built-in themes to get started, and then progress to something more bespoke later on as their site grows. </p><p>The best way to get started is with Ghost's branding settings, where you can set up colors, images and logos to fit with your brand.</p><figure class=\"kg-card kg-image-card kg-width-wide kg-card-hascaption\"><img src=\"https://static.ghost.org/v4.0.0/images/brandsettings.png\" class=\"kg-image\" alt=\"\" loading=\"lazy\" width=\"3456\" height=\"2338\"><figcaption>Ghost Admin → Settings → Branding</figcaption></figure><p>Any Ghost theme that's up to date and compatible with Ghost 4.0 and higher will reflect your branding settings in the preview window, so you can see what your site will look like as you experiment with different options.</p><p>When selecting an accent color, try to choose something which will contrast well with white text. Many themes will use your accent color as the background for buttons, headers and navigational elements. Vibrant colors with a darker hue tend to work best, as a general rule.</p><h2 id=\"installing-ghost-themes\">Installing Ghost themes</h2><p>By default, new sites are created with Ghost's friendly publication theme, called Casper. Everything in Casper is optimized to work for the most common types of blog, newsletter and publication that people create with Ghost — so it's a perfect place to start.</p><p>However, there are hundreds of different themes available to install, so you can pick out a look and feel that suits you best.</p><figure class=\"kg-card kg-image-card kg-width-wide kg-card-hascaption\"><img src=\"https://static.ghost.org/v4.0.0/images/themesettings.png\" class=\"kg-image\" alt=\"\" loading=\"lazy\" width=\"3208\" height=\"1618\"><figcaption>Ghost Admin → Settings → Theme</figcaption></figure><p>Inside Ghost's theme settings you'll find 4 more official themes that can be directly installed and activated. Each theme is suited to slightly different use-cases.</p><ul><li><strong>Casper</strong> <em>(default)</em> — Made for all sorts of blogs and newsletters</li><li><strong>Edition</strong> — A beautiful minimal template for newsletter authors</li><li><strong>Alto</strong> — A slick news/magazine style design for creators</li><li><strong>London</strong> — A light photography theme with a bold grid</li><li><strong>Ease</strong> — A library theme for organizing large content archives</li></ul><p>And if none of those feel quite right, head on over to the <a href=\"https://ghost.org/themes/\">Ghost Marketplace</a>, where you'll find a huge variety of both free and premium themes.</p><h2 id=\"building-something-custom\">Building something custom</h2><p>Finally, if you want something completely bespoke for your site, you can always build a custom theme from scratch and upload it to your site.</p><p>Ghost's theming template files are very easy to work with, and can be picked up in the space of a few hours by anyone who has just a little bit of knowledge of HTML and CSS. Templates from other platforms can also be ported to Ghost with relatively little effort.</p><p>If you want to take a quick look at the theme syntax to see what it's like, you can <a href=\"https://github.com/tryghost/casper/\">browse through the files of the default Casper theme</a>. We've added tons of inline code comments to make it easy to learn, and the structure is very readable.</p><figure class=\"kg-card kg-code-card\"><pre class=\" language-javascript\" tabindex=\"0\"><code class=\" language-javascript\"><span class=\"token keyword\">import</span> <span class=\"token punctuation\">{</span> MongoClient <span class=\"token punctuation\">}</span> <span class=\"token keyword\">from</span> <span class=\"token string\">'mongodb'</span>\n\n<span class=\"token keyword\">let</span> uri <span class=\"token operator\">=</span> process<span class=\"token punctuation\">.</span>env<span class=\"token punctuation\">.</span><span class=\"token constant\">MONGODB_URI</span> <span class=\"token operator\">||</span> <span class=\"token string\">\"\"</span> <span class=\"token comment\">// trick ts :(</span>\n<span class=\"token keyword\">let</span> dbName <span class=\"token operator\">=</span> process<span class=\"token punctuation\">.</span>env<span class=\"token punctuation\">.</span><span class=\"token constant\">MONGODB_DB</span>\n\n<span class=\"token keyword\">let</span> cachedClient<span class=\"token operator\">:</span> any <span class=\"token operator\">=</span> <span class=\"token keyword\">null</span>\n<span class=\"token keyword\">let</span> cachedDb<span class=\"token operator\">:</span> any <span class=\"token operator\">=</span> <span class=\"token keyword\">null</span>\n\n<span class=\"token keyword\">if</span> <span class=\"token punctuation\">(</span><span class=\"token operator\">!</span>uri<span class=\"token punctuation\">)</span> <span class=\"token punctuation\">{</span>\n  <span class=\"token keyword\">throw</span> <span class=\"token keyword\">new</span> <span class=\"token class-name\">Error</span><span class=\"token punctuation\">(</span>\n    <span class=\"token string\">'Please define the MONGODB_URI environment variable inside .env.local'</span>\n  <span class=\"token punctuation\">)</span>\n<span class=\"token punctuation\">}</span>\n\n<span class=\"token keyword\">if</span> <span class=\"token punctuation\">(</span><span class=\"token operator\">!</span>dbName<span class=\"token punctuation\">)</span> <span class=\"token punctuation\">{</span>\n  <span class=\"token keyword\">throw</span> <span class=\"token keyword\">new</span> <span class=\"token class-name\">Error</span><span class=\"token punctuation\">(</span>\n    <span class=\"token string\">'Please define the MONGODB_DB environment variable inside .env.local'</span>\n  <span class=\"token punctuation\">)</span>\n<span class=\"token punctuation\">}</span>\n\n<span class=\"token keyword\">export</span> <span class=\"token keyword\">async</span> <span class=\"token keyword\">function</span> <span class=\"token function\">connectToDatabase</span><span class=\"token punctuation\">(</span><span class=\"token punctuation\">)</span> <span class=\"token punctuation\">{</span>\n  <span class=\"token keyword\">if</span> <span class=\"token punctuation\">(</span>cachedClient <span class=\"token operator\">&amp;&amp;</span> cachedDb<span class=\"token punctuation\">)</span> <span class=\"token punctuation\">{</span>\n    <span class=\"token keyword\">return</span> <span class=\"token punctuation\">{</span> client<span class=\"token operator\">:</span> cachedClient<span class=\"token punctuation\">,</span> db<span class=\"token operator\">:</span> cachedDb <span class=\"token punctuation\">}</span>\n  <span class=\"token punctuation\">}</span>\n\n  <span class=\"token keyword\">const</span> client <span class=\"token operator\">=</span> <span class=\"token keyword\">await</span> MongoClient<span class=\"token punctuation\">.</span><span class=\"token function\">connect</span><span class=\"token punctuation\">(</span>uri<span class=\"token punctuation\">,</span> <span class=\"token punctuation\">{</span>\n    useNewUrlParser<span class=\"token operator\">:</span> <span class=\"token boolean\">true</span><span class=\"token punctuation\">,</span>\n    useUnifiedTopology<span class=\"token operator\">:</span> <span class=\"token boolean\">true</span><span class=\"token punctuation\">,</span>\n  <span class=\"token punctuation\">}</span><span class=\"token punctuation\">)</span>\n\n  <span class=\"token keyword\">const</span> db <span class=\"token operator\">=</span> <span class=\"token keyword\">await</span> client<span class=\"token punctuation\">.</span><span class=\"token function\">db</span><span class=\"token punctuation\">(</span>dbName<span class=\"token punctuation\">)</span>\n\n  cachedClient <span class=\"token operator\">=</span> client\n  cachedDb <span class=\"token operator\">=</span> db\n\n  <span class=\"token keyword\">return</span> <span class=\"token punctuation\">{</span> client<span class=\"token punctuation\">,</span> db <span class=\"token punctuation\">}</span>\n<span class=\"token punctuation\">}</span></code></pre><figcaption>A snippet from a post template</figcaption></figure><p>See? Not that scary! But still completely optional. </p><p>If you're interested in creating your own Ghost theme, check out our extensive <a href=\"https://ghost.org/docs/themes/\">theme documentation</a> for a full guide to all the different template variables and helpers which are available.</p>" Client: "<p>As discussed in the <a href=\"https://mage-css.ghost.io/welcome/\">introduction</a> post, one of the best things about Ghost is just how much you can customize to turn your site into something unique. Everything about your layout and design can be changed, so you're not stuck with yet another clone of a social network profile.</p><p>How far you want to go with customization is completely up to you, there's no right or wrong approach! The majority of people use one of Ghost's built-in themes to get started, and then progress to something more bespoke later on as their site grows. </p><p>The best way to get started is with Ghost's branding settings, where you can set up colors, images and logos to fit with your brand.</p><figure class=\"kg-card kg-image-card kg-width-wide kg-card-hascaption\"><img src=\"https://static.ghost.org/v4.0.0/images/brandsettings.png\" class=\"kg-image\" alt=\"\" loading=\"lazy\" width=\"3456\" height=\"2338\"><figcaption>Ghost Admin → Settings → Branding</figcaption></figure><p>Any Ghost theme that's up to date and compatible with Ghost 4.0 and higher will reflect your branding settings in the preview window, so you can see what your site will look like as you experiment with different options.</p><p>When selecting an accent color, try to choose something which will contrast well with white text. Many themes will use your accent color as the background for buttons, headers and navigational elements. Vibrant colors with a darker hue tend to work best, as a general rule.</p><h2 id=\"installing-ghost-themes\">Installing Ghost themes</h2><p>By default, new sites are created with Ghost's friendly publication theme, called Casper. Everything in Casper is optimized to work for the most common types of blog, newsletter and publication that people create with Ghost — so it's a perfect place to start.</p><p>However, there are hundreds of different themes available to install, so you can pick out a look and feel that suits you best.</p><figure class=\"kg-card kg-image-card kg-width-wide kg-card-hascaption\"><img src=\"https://static.ghost.org/v4.0.0/images/themesettings.png\" class=\"kg-image\" alt=\"\" loading=\"lazy\" width=\"3208\" height=\"1618\"><figcaption>Ghost Admin → Settings → Theme</figcaption></figure><p>Inside Ghost's theme settings you'll find 4 more official themes that can be directly installed and activated. Each theme is suited to slightly different use-cases.</p><ul><li><strong>Casper</strong> <em>(default)</em> — Made for all sorts of blogs and newsletters</li><li><strong>Edition</strong> — A beautiful minimal template for newsletter authors</li><li><strong>Alto</strong> — A slick news/magazine style design for creators</li><li><strong>London</strong> — A light photography theme with a bold grid</li><li><strong>Ease</strong> — A library theme for organizing large content archives</li></ul><p>And if none of those feel quite right, head on over to the <a href=\"https://ghost.org/themes/\">Ghost Marketplace</a>, where you'll find a huge variety of both free and premium themes.</p><h2 id=\"building-something-custom\">Building something custom</h2><p>Finally, if you want something completely bespoke for your site, you can always build a custom theme from scratch and upload it to your site.</p><p>Ghost's theming template files are very easy to work with, and can be picked up in the space of a few hours by anyone who has just a little bit of knowledge of HTML and CSS. Templates from other platforms can also be ported to Ghost with relatively little effort.</p><p>If you want to take a quick look at the theme syntax to see what it's like, you can <a href=\"https://github.com/tryghost/casper/\">browse through the files of the default Casper theme</a>. We've added tons of inline code comments to make it easy to learn, and the structure is very readable.</p><figure class=\"kg-card kg-code-card\"><pre><code class=\"language-javascript\">import { MongoClient } from 'mongodb'\n\nlet uri = process.env.MONGODB_URI || \"\" // trick ts :(\nlet dbName = process.env.MONGODB_DB\n\nlet cachedClient: any = null\nlet cachedDb: any = null\n\nif (!uri) {\n  throw new Error(\n    'Please define the MONGODB_URI environment variable inside .env.local'\n  )\n}\n\nif (!dbName) {\n  throw new Error(\n    'Please define the MONGODB_DB environment variable inside .env.local'\n  )\n}\n\nexport async function connectToDatabase() {\n  if (cachedClient &amp;&amp; cachedDb) {\n    return { client: cachedClient, db: cachedDb }\n  }\n\n  const client = await MongoClient.connect(uri, {\n    useNewUrlParser: true,\n    useUnifiedTopology: true,\n  })\n\n  const db = await client.db(dbName)\n\n  cachedClient = client\n  cachedDb = db\n\n  return { client, db }\n}</code></pre><figcaption>A snippet from a post template</figcaption></figure><p>See? Not that scary! But still completely optional. </p><p>If you're interested in creating your own Ghost theme, check out our extensive <a href=\"https://ghost.org/docs/themes/\">theme documentation</a> for a full guide to all the different template variables and helpers which are available.</p>"
    at div
    at article
    at PostBody (webpack-internal:///./components/UI/Organisms/PostBody/index.tsx:30:22)
    at section
    at Article (webpack-internal:///./components/UI/Atoms/Section/index.tsx:15:23)
    at main
    at Layout (webpack-internal:///./components/UI/Molecules/Layout/index.tsx:19:22)
    at PostTemplate (webpack-internal:///./components/Templates/Post/index.tsx:28:19)
    at Index (webpack-internal:///./pages/posts/[slug].tsx:27:19)
    at MyApp (webpack-internal:///./pages/_app.tsx:39:24)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:254:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:750:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:889:25)

**Comment by RunDevelopment** [comment] 2021-08-18 10:44
Ok. Then I know what's going on. 

The warning essentially says that React's virtual DOM and the actual DOM are out of sync. React makes the assumption that it is the only one that can make modifications to the DOM. You broke that assumption by using `Prism.highlightAll()`.

So how can we fix that? Well, let's just highlight all code before we pass it to React.

```js
function highlightCodeInHTML(html: string): string {
	const container = document.createElement("div");
	container.innerHTML = html; // unsafe but whatever

	Prism.highlightAllUnder(container);

	return container.innerHTML;
}
```


---

Full example:

```tsx
import PostStyle from "./post-styles.module.css";
import styles from "./style.module.css";
import CardImage from "../../Molecules/CardImage";
import Prism from "prismjs";
import { useEffect } from "react";
type Props = {
  content: string;
  thumbnail: string;
  title: string;
};

const PostBody = ({ content, thumbnail, title }: Props) => {
  return (
    <>
      <CardImage src={thumbnail} alt={title} />
      <article className={styles.section__article}>
        <div
          className={`${PostStyle["post"]}`}
          dangerouslySetInnerHTML={{ __html: highlightCodeInHTML(content) }}
        />
      </article>
    </>
  );
};

function highlightCodeInHTML(html: string): string {
	const container = document.createElement("div");
	container.innerHTML = html; // unsafe but whatever

	Prism.highlightAllUnder(container);

	return container.innerHTML;
}

export default PostBody;
```

(I would recommend you don't call `highlightCodeInHTML` on every render.)

**Comment by lucasfernandodev** [comment] 2021-08-18 11:04
I tried it and now it's showing a `ReferenceError: document is not defined`

**Comment by RunDevelopment** [comment] 2021-08-18 11:50
So you have an SSR setup? That makes things more complex.

My suggestion would be to use [JSDom](https://github.com/jsdom/jsdom) on the server and the regular browser DOM in the browser. Kinda like this:

```ts
const doc = typeof document === "undefined" 
  ? new JSDOM("").window.document
  : document;

function highlightCodeInHTML(html: string): string {
	const container = doc.createElement("div");
	container.innerHTML = html; // unsafe but whatever

	Prism.highlightAllUnder(container);

	return container.innerHTML;
}
```

This does mean that your client-side website will include JSDom but maybe you can find a way to exclude it in the browser.

**Comment by RunDevelopment** [comment] 2021-08-18 11:53
I will close the issue now. The problem isn't Prism but how it is used.

This doesn't mean that the conversation ends here. Feel free to keep commenting. I'm also interested in knowing whether my suggested solution works.

**Closed by RunDevelopment** 2021-08-18 11:53 UTC

**Comment by lucasfernandodev** [comment] 2021-08-18 11:54
I got it using useState and useEffect but I'm not sure it's performatico.::
```
import PostStyle from "./post-styles.module.css";
import styles from "./style.module.css";
import CardImage from "../../Molecules/CardImage";
import Prism from "prismjs";
import { useEffect, useState } from "react";
type Props = {
  content: string;
  thumbnail: string;
  title: string;
};

const PostBody = ({ content, thumbnail, title }: Props) => {
  const [post, setPost] = useState("loading...");
  useEffect(() => {
    function highlightCodeInHTML(html: string): string {
      const container = document.createElement("div");
      container.innerHTML = html; // unsafe but whatever

      Prism.highlightAllUnder(container);

      return container.innerHTML;
    }
    setPost(highlightCodeInHTML(content));
  }, []);
  return (
    <>
      <CardImage src={thumbnail} alt={title} />
      <article className={styles.section__article}>
        <div
          className={`${PostStyle["post"]}`}
          dangerouslySetInnerHTML={{ __html: post }}
        />
      </article>
    </>
  );
};

export default PostBody;
```

Thank you for your help!

**Comment by RunDevelopment** [comment] 2021-08-18 12:05
> I got it using useState and useEffect

That's an even better solution. 

> but I'm not sure it's performatico.::

React should be smart enough to cache things here. Should be fine.

**Comment by mAAdhaTTah** [comment] 2021-08-18 12:48
Your initial solution might be fine if you disable automatic highlighting with `Prism.manual = true`. The problem is the highlight in your initial useEffect isn't actually the first highlight, and it's happening before React runs, hence the mismatch.
