### ISSUE TITLE
Q: When will Prism 1.16 be released?

### ISSUE THREAD

**Issue by ExE-Boss** [PrismJS/prism#1728] opened 2019-02-13 02:00 UTC
I’d like to&nbsp;know when **Prism&nbsp;1.16** might be&nbsp;released, so&nbsp;that I&nbsp;can know whether https://github.com/mozilla/kuma/pull/5189 should be&nbsp;merged now or&nbsp;if&nbsp;we&nbsp;should wait for&nbsp;**Prism&nbsp;1.16**, which will include&nbsp;https://github.com/PrismJS/prism/pull/1595, https://github.com/PrismJS/prism/pull/1660 and&nbsp;https://github.com/PrismJS/prism/pull/1727.

/cc @jwhitlock, @schalkneethling

**Comment by mAAdhaTTah** [comment] 2019-02-13 12:59
Bah, I've been saying I was going to take care of that for weeks. Sorry for the delay. In the meantime, you can download the latest version from the website, but yeah, I need to publish the latest.

Dupe of #1713.

**Closed by mAAdhaTTah** 2019-02-13 12:59 UTC

**Comment by mAAdhaTTah** [comment] 2019-03-25 11:39
🎉 [1.16.0](https://github.com/PrismJS/prism/releases/tag/v1.16.0) is finally released! 🎉
