### ISSUE TITLE
Code Mirror pushing to Prism stripping out closing HTML brackets, "</" are missing

### ISSUE THREAD

**Issue by Dcmorris101** [PrismJS/prism#2026] opened 2019-08-24 02:32 UTC
**Information:**
- Prism version: PrismJS 1.17.1
- Environment: Code MIrror, Browser

Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue?
Yes

**Description**
I am using code mirror to push written code into a prism box for easy writing and easy viewing. I am getting the innerHTML value and passing it straight to prism for styling. When I write a block of HTML specifically (all other languages work), the output of the final product strips out the closing bracket and slash and puts it into an HTML comment.

The image below shows an example. The left is the output while the right is what the dev tools is showing.

![prism issue](https://user-images.githubusercontent.com/37924444/63631438-7b159600-c5dc-11e9-9bf0-351bf79442bf.PNG)

The code input into Code Mirror is the following:
```
<script type="text/plain">
<div class="singleitem" data-repeating-id="repeating-content">
  <div class="testing">
      <section id="test-id">
        <p>Some things work and some don't.</p>
      </section>
  </div>
</div>
</script>

```

**Comment by RunDevelopment** [comment] 2019-08-24 07:38
Seems like a double-unescape issue. Could you please post the code which uses Prism to highlight the Code Mirror text and the code which inserts the Prism output into the DOM?

**Comment by Dcmorris101** [comment] 2019-08-25 00:30
> Seems like a double-unescape issue. Could you please post the code which uses Prism to highlight the Code Mirror text and the code which inserts the Prism output into the DOM?

I'm not 100% sure if this is what you're asking for since it's a bit of a customized solution we have, but the DOM is essentially created through cases of data-types, if it is the data-type of a code block editor, it does the following:

```
    case "codeblockeditor":
      var o = {"Column": colNameInternal, "ID": internalID, "OnChange": CopyCodeMirrorToSource, "OnSave": CopyCodeMirrorToSource};
      var tag="textarea";
      $("._moduleSettings").html("<div style='font-weight:bold;font-size:18px;'>Place your code below:</div><"+tag+" id='CodeMirrorEditor_TextArea' style='width:100%;height:75%;'>" + source.html() + "</"+tag+">");
      $("#CodeMirrorEditor_TextArea").CreateCodeMirrorEditor(o); // Creates an instance of a code mirror editor
      break;
```

and later:

```
var CopyCodeMirrorToSource = function() {
  var activeParam = $(".paramName.active");
  var paramValueNode = activeParam.next(".paramValue");
  var fix = paramValueNode.html($.fn.CreateCodeMirrorEditor.ActiveEditor.getValue())[0].innerHTML;
  paramValueNode.html(fix);
  paramValueNode.trigger("change"); 
  $(".ToolBar ._rtSave").remove();
}
```

So basically the user is inserting code in a preview window via code mirror, and every change/save it is being pulled into the DOM. The styling/highlighting for the prism syntax is just taken from the default Prism JS and CSS files that were downloaded from the site. Let me know if this isn't helpful.

**Comment by RunDevelopment** [comment] 2019-08-25 07:18
Unfortunately, that isn't enough for me to pin down the problem. Could you please also provide the code which calls any of Prism highlight functions?

Also, Prism doesn't use the `innerHTML` property of an element to extract the code to be highlighted; It uses `textContent`. Maybe that's the cause of the issue?

Also also, have you verified that it's actually Prism causing parts of the user's code to disappear?

**Comment by RunDevelopment** [comment] 2019-08-26 19:19
Use your browser's debugger. [This](https://github.com/PrismJS/prism/blob/9f7225864143369ef7f092f657d148318a7a151c/components/prism-core.js#L215) is the line where you want to set the breakpoint. It's where Prism extracts the text. From what I heard from you, the problem most likely lies somewhere in your customized solution, so I will close this for now.
From this line, you should be able to backtrack to the cause of this issue.

Unfortunately, without a look into your code, I can't help you more than that.

**Closed by RunDevelopment** 2019-08-26 19:19 UTC
