### ISSUE TITLE
When creating a new language, keywords do not work if they are not in English

### ISSUE THREAD

**Issue by Diversus23** [PrismJS/prism#2519] opened 2020-08-13 12:58 UTC
**Information:**
- Prism version: 1.21.0
- Plugins: none
- Environment: Chrome, npm 6.14.6,

**Description**
I made a new language  BSL (1C:Enterprise) https://github.com/Diversus23/prism 
In Russia, the popular development environment 1C:Enterprise 8. It is possible to use two language in the development of Russian and English. For example:

```
While a = 1 Do
...
EndDo;

```
Analog in Russian:

```
Пока а = 1 Цикл
...
КонецЦикла;
```

I use flag /u for RegExp (for Unicode characters), but but it doesn't work for Russian language (for English ok)... How do I fix this?

Pattern:

```
	'keyword': [
		{
			// RU
			pattern: /\b(?:пока|для|новый|прервать|...|конеццикла)\b/uig,
			lookbehind: true		
		},
		{
			// Eng
			pattern: /\b(?:while|for|new|break|try|...|enddo)\b/ig,
			lookbehind: true
		}
	],
```

Screenshots:

![2020-08-13_15-48-27](https://user-images.githubusercontent.com/19926084/90136360-bcb6c800-dd7c-11ea-8571-fe4c7ca1ddd7.png)
![2020-08-13_15-49-08](https://user-images.githubusercontent.com/19926084/90136362-bde7f500-dd7c-11ea-9e96-a16c96693948.png)
![2020-08-13_15-49-43](https://user-images.githubusercontent.com/19926084/90136363-be808b80-dd7c-11ea-8068-dd328f39ef0c.png)

**Example**
An example which reproduces the bug. This can be a link to a website, a [JSFiddle](https://jsfiddle.net/), an attached example project, etc.

**Comment by RunDevelopment** [comment] 2020-08-13 13:26
The problem is `\b`.

`\b` means word boundary where a word is defined as a `\w` character. But `\w` only includes the letters A-Z (uppercase and lowercase), digits 0-9 (ASCII only), and the underscore (`_`). That's it; It doesn't include any non-Latin characters. This doesn't change when adding the `u` flag.

So from the perspective of `\b`, all Russian characters are non-word characters, meaning that there is no word boundary between `(` and `п` because neither are word characters.

__Workaround 1__

As per specification, `\b` is the same as `(?:(?<=\w)(?!\w)|(?<!\w)(?=\w))`. If we want the boundary of letters and digits of any language, we can simply replace the `\w`s with `[\p{L}\p{N}_]` to get `(?:(?<=[\p{L}\p{N}_])(?![\p{L}\p{N}_])|(?<![\p{L}\p{N}_])(?=[\p{L}\p{N}_]))` (requires the `u` flag). You can use this monster as a drop-in replacement for `\b`.

The only problem with this workaround is browser support. Both Unicode properties and ES2018 lookbehinds are fairly new. While you can use Babel to transpile Unicode properties to support older browsers, ES2018 lookbehinds require native browser support.

__Workaround 2__

If you only need the boundaries for keyword lists (e.g. `(?:пока|для|новый|прервать|...|конеццикла)`), then we can use Prism's lookbehind groups to do so. It's done like this:

```js
	'keyword': [
		{
			// RU
			pattern: /(^|[^\p{L}\p{N}_])(?:пока|для|новый|прервать|...|конеццикла)(?![\p{L}\p{N}_])/iu,
			lookbehind: true
		},
		{
			// Eng
			pattern: /(^|[^\p{L}\p{N}_])(?:while|for|new|break|try|...|enddo)(?![\p{L}\p{N}_])/iu,
			lookbehind: true
		}
	],
```

Again, the problem is browser support but if you use Babel to transpile the Unicode properties, you will be able to support older browsers. We didn't use ES2018 lookbehinds, so they aren't an issue.

I hope this solves your problem.

**Comment by Diversus23** [comment] 2020-08-13 14:42
> I hope this solves your problem.

Yes it work!
This is pattern:

`(?:(?<=[\p{L}\p{N}_])(?![\p{L}\p{N}_])|(?<![\p{L}\p{N}_])`

It looks like sorcery :)

**Comment by Diversus23** [comment] 2020-08-13 15:21
One moment.
If use Workaround 1 not work "npm test"
If use Workaround not work both tests "npm run test:languages -- --language=bsl --pretty" and "npm test"

**Comment by RunDevelopment** [comment] 2020-08-13 16:13
I will close this issue now because regex itself works. Let's continue the discussion on how to make the tests pass in #2520.

**Closed by RunDevelopment** 2020-08-13 16:13 UTC
