### ISSUE TITLE
gatsby-remark-prismjs Horizontal Overflow

### ISSUE THREAD

**Issue by jrock2004** [PrismJS/prism#3392] opened 2022-03-13 20:18 UTC
**Information:**
- Prism version: 1.27.0
- Plugins: gatsby-transformer-remark, gatsby-remark-prismjs
- Environment: OSX, Firefox, Gatsby

**Description**

Having issues with prism overflowing on mobile

![image](https://user-images.githubusercontent.com/655716/158077447-d09f47c3-2e6e-45d5-82e5-8c40d9bb12e6.png)

If I do the following it will not overflow 

```css
.gatsby-highlight {
  max-width: 350px;
}
```

If I set a percentage it will overflow again. Maybe I am missing something?

**Comment by RunDevelopment** [comment] 2022-03-14 10:20
Hello @jrock2004.

I don't think we can help you with this for two reasons:

1. We (the Prism team) have nothing to do with Gatsby and its plugins. If the issue is caused by Gatsby, we won't be able to help you. 
    You mentioned a `gatsby-highlight` class. This class isn't something that Prism uses.
2. You did not provide enough information. I cannot replicate or debug your issue. Frankly, I'm not even sure what the screenshot shows exactly.

I suggest you [open an issue over at gatsbyjs/gatsby](https://github.com/gatsbyjs/gatsby/issues) or use their [help discussion page](https://github.com/gatsbyjs/gatsby/discussions/categories/help). They are the experts when it comes to Gatsby.

I'm sorry for closing this, but I don't think we'll be able to help you with your issue.

**Closed by RunDevelopment** 2022-03-14 10:20 UTC
