### ISSUE TITLE
prism sudennly stopped working

### ISSUE THREAD

**Issue by rtwk** [PrismJS/prism#2673] opened 2020-12-11 12:56 UTC
I have been using prism on my website for several years. Suddenly I found that it is failing to highlight syntax from today morning. I was using a version 1.15 and I upgraded it wth 1.22; still it is not working. I found one strange thing; when I pasted the js code within script tag, I found that the closing script tag is grey as if there is an error in the script inside. Anybody else facing the same issue? How to fix it?

**Comment by rtwk** [comment] 2020-12-11 14:05
So, now the syntax highlighting is coming properly but no line numbering.

**Comment by edukisto** [comment] 2020-12-11 14:36
> ...when I pasted the js code within script tag, I found that the closing script tag is grey as if there is an error in the script inside.

Could you please show us the JS code, the tags, and the error message?

How do you include Prism?

**Comment by RunDevelopment** [comment] 2020-12-11 15:32
@rtwk As @edukisto said, we need a way to reproduce your issue or else there nothing we can do.

**Comment by rtwk** [comment] 2020-12-12 08:59
I included css code within a style tag. JS file is invoked in a script tag now, instead of including that inline. now the syntax highlighting is coming properly but no line numbering and copy option. There is also a space on the left hand side.

**Comment by RunDevelopment** [comment] 2020-12-12 15:13
@rtwk I'm sorry but this is not enough to reproduce your issue. 

Could you please provide a working example of your issue in action? Anything that I can run on my machine is fine (e.g. JSFiddle, or a small example project [attached as a `.zip` file](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests#:~:text=To%20attach%20a%20file%20to,images%20directly%20into%20the%20box.)).

**Comment by rtwk** [comment] 2020-12-12 16:06
It is seems it is working now. I am attaching a zip file for your reference. Thank you for your support. 
[prism_test.zip](https://github.com/PrismJS/prism/files/5683361/prism_test.zip)

**Comment by RunDevelopment** [comment] 2020-12-12 16:53
There is one issue with your file: the spaces between the `pre` and `code` tags.

Replacing

```html
<pre class="line-numbers">
<code class="language-python">def find_longest_word(words_list):
    ...
</code>
</pre>
```

with 

```html
<pre class="line-numbers"><code class="language-python">def find_longest_word(words_list):
    ...
</code></pre>
```

will fix the issue with Coy. Some plugins like Line numbers and Toolbar also have have problems with these spaces, so please make sure to remove them all.

Apart from the spaces, everything seems to be alright. I'm closing this issue now.

**Closed by RunDevelopment** 2020-12-12 16:53 UTC
