### ISSUE TITLE
Extra attributes from the server: class,tabindex

### ISSUE THREAD

**Issue by sytpb** [PrismJS/prism#3519] opened 2022-08-17 02:05 UTC
Information: for prismjs 2.1.0 in Next.js 12.2.4

package.json 

  "dependencies": {
    "babel-plugin-prismjs": "^2.1.0",
    "next": "12.2.4",
    "prismjs": "^1.28.0",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },

.babelrc
{
    "presets": ["next/babel"],
    "plugins": [
      [
        "prismjs",
        {
          "languages": ["javascript", "css", "markup"],
          "plugins": ["line-numbers"],
          "theme": "twilight",
          "css": true
        }
      ]
    ]
}

**Description**
![image](https://user-images.githubusercontent.com/12178686/185018164-e21eb6eb-5714-4549-9187-e76c80b99f59.png)

now it runs ok ,but there is a warning look weird

**Comment by RunDevelopment** [comment] 2022-08-17 08:48
Duplicate of #3521.

**Closed by RunDevelopment** 2022-08-17 08:48 UTC
