### ISSUE TITLE
Not the good number of lines

### ISSUE THREAD

**Issue by lcswillems** [PrismJS/prism#1946] opened 2019-06-18 13:14 UTC
Hi,

I tried the line numbers plugin. However, with the following code:

```
<pre class="line-numbers"><code class="language-latex">\section{Hi}

\begin{itemize}
\item Hi
\end{itemize}</code></pre>
```

I get the following output:

![image](https://user-images.githubusercontent.com/5437552/59685138-c3c76200-91db-11e9-9211-3736b04fbd74.png)

Any idea?

**Comment by lcswillems** [comment] 2019-06-18 13:15
There is the good number!! I just don't have the good line height. Sorry for that!

**Comment by lcswillems** [comment] 2019-06-18 13:19
However, how can I change the line height of the line numbers ?

**Comment by RunDevelopment** [comment] 2019-06-18 13:25
It's important that both the `pre` and `code` elements [have the same line height](https://github.com/PrismJS/prism/blob/f571cfce19c7a13df375a2fd921b64e16fa6e71e/themes/prism.css#L19). You don't seem to use one of Prism's default themes, so I guess that that's the issue.

Btw. What theme is that?

**Comment by lcswillems** [comment] 2019-06-18 13:29
It is the Github theme: https://github.com/PrismJS/prism-themes/blob/master/themes/prism-ghcolors.css

This is strange with the default theme. The line numbers have the good line-height but with this theme they don't...

**Comment by RunDevelopment** [comment] 2019-06-18 14:12
Alright. The problem is the following [line](https://github.com/PrismJS/prism-themes/blob/dc4f1b741ea9b21e72ad64e2565c00c84da66e84/themes/prism-ghcolors.css#L15): 

```css
code[class*="language-"],
pre[class*="language-"] {
    ...
    font-size: 0.95em;
    ...
}
```

This means that for a code block `<pre><code>`, the font size of `pre` and `code` is 95% of their parent. The parent of `code` is `pre`, so effectively, the code will be displayed at 90.25% font size.

I don't quite get why, but just enforcing that the font size of `code` is 100% fixes the issue.
I'll make a PR with the fix.

**Comment by lcswillems** [comment] 2019-06-18 14:54
In fact, your fix works for me!

Thank you :)

**Comment by mAAdhaTTah** [comment] 2019-09-04 14:37
Going to close this issue, since the fix is in prism-themes.

**Closed by mAAdhaTTah** 2019-09-04 14:37 UTC
Labels: bug, plugins, themes
