### ISSUE TITLE
Line number issue in IE9

### ISSUE THREAD

**Issue by sujilesh** [PrismJS/prism#159] opened 2013-08-30 12:57 UTC
In IE all the line numbers still go to zero when you go back from Schema tab to Example tab, here I'm using ui-tabs too. 

For more Info, please find the attached image
![img_29082013_113124](https://f.cloud.github.com/assets/4026863/1057437/b2fc33d6-1173-11e3-806d-c90c40e577b0.png)
![img_30082013_113108](https://f.cloud.github.com/assets/4026863/1057438/b2f72904-1173-11e3-88dd-bef149004bad.png)

**Comment by loganfranken** [comment] 2015-06-20 05:53
Hey @sujilesh, do you have a live example of this?

When I embedded the latest Prism in a fiddle, I wasn't able to recreate the problem:
https://jsfiddle.net/8rzwq5sp/

Maybe the issue has been fixed?

**Comment by loganfranken** [comment] 2015-06-28 00:45
Hey @Golmote, I think we can close this issue since I'm unable to reproduce it.

(Unless you can, @sujilesh?)

**Comment by Golmote** [comment] 2015-06-28 00:52
Not reproduced.

**Closed by Golmote** 2015-06-28 00:52 UTC
Labels: bug, plugins

**Comment by sujilesh** [comment] 2015-06-28 04:00
Hello, I have tried the same issue with latest prism its not replicable. Working fine in  IE9.

Thanks
Sujilesh
