### ISSUE TITLE
Suggestion: Release on CDNJS.com

### ISSUE THREAD

**Issue by wmh** [PrismJS/prism#158] opened 2013-08-28 16:33 UTC
CDNJS is a free Content Delivery Network hosted by CloudFlare for open source, community-driven projects. It would be great to release prism on CDNJS for all to use.

Instructions to add a project to CDNJS:
https://github.com/cdnjs/cdnjs

PS. Or you can simply add a tag to current version, and I'll do the rest.
```
git tag 1.0.0
git push --tags
```

**Comment by loganfranken** [comment] 2015-06-20 05:31
It looks like someone did this (wahoo!):
https://cdnjs.com/libraries/prism

I think this can be closed.

**Comment by Golmote** [comment] 2015-06-20 11:00
The version is outdated. I guess since we now have [release 1.0.0](https://github.com/PrismJS/prism/releases), something can be done to update CDNJS.

**Comment by thednp** [comment] 2015-10-06 14:36
Please change/add CDN provider. I use <a href="https://github.com/jsdelivr/jsdelivr">jsDeliver</a>, it automatically adds new release tags to clouds.
The 0.0.1 version on cdnjs is pretty buggy with JS.

**Comment by Golmote** [comment] 2015-10-08 07:20
@thednp I configured the autopupdate on jsdelivr. (https://github.com/jsdelivr/jsdelivr/tree/master/files/prism)

**Comment by thednp** [comment] 2015-10-08 12:47
Thanks, as I can see the jsdeliver repository, there is no prism.min.js and prism.min.css, so you better check that too.

**Comment by Golmote** [comment] 2015-10-08 13:34
No, there are all temes, all components (minified), all plugins (minified) and a default prism.js file that is mainly used for Prism's website, currently. We can argue about the minification of the themes, but well, I think we're ok for now.

**Comment by Golmote** [comment] 2016-07-05 16:46
Both CDNJS and jsDeliver look up to date. I'm closing this issue.

**Closed by Golmote** 2016-07-05 16:46 UTC

**Comment by wmh** [comment] 2016-07-05 22:56
:+1:

**Comment by NullVoxPopuli** [comment] 2018-05-17 21:14
Is there a simple example / html file that demonstrates how to use the cdn?

**Comment by Golmote** [comment] 2018-05-18 06:02
@NullVoxPopuli Unfortunately, using the CDN, you need to handle language dependencies yourself.

Handlebars requires Markup-templating, so a working example would be: https://codesandbox.io/s/3vx76wq76m

**Comment by hades200082** [comment] 2018-05-20 12:45
Why not put a "Complete" js on CDN that includes all languages... and each theme css as individual CDN files.  that way the developer only has two files to include from CDN.

If anyone doesn't want everything included they can still build their own version.

**Comment by mAAdhaTTah** [comment] 2018-05-20 15:01
@Golmote You wouldn't want to use it in production, but if you're pulling together like a small demo or something, it would be easier setup than figuring out exactly what languages you need. The counterpoint is it could easily be a "go-to" when people have problems (e.g. the `markup-templating` issue) that blows up their site weight without thinking deeply about what the problem is.

**Comment by Golmote** [comment] 2018-05-20 17:03
@mAAdhaTTah That's definitely what I'm worried about. I guess we could add a message warning about the file size, so that we don't hold the responsability...

**Comment by mAAdhaTTah** [comment] 2018-05-20 17:28
Just to take a step back, what's the use case / user flow that we're trying to solve here? @hades200082 since you made the suggestion, how are you thinking about using it?
