### ISSUE TITLE
Double slashes in PHP strings

### ISSUE THREAD

**Issue by ethanhowell** [PrismJS/prism#1097] opened 2017-02-09 02:18 UTC
If I have two backslashes in a php string, Prism will mark the rest of the line as a comment.
![example](https://cloud.githubusercontent.com/assets/21162595/22766544/57f7502e-ee33-11e6-8827-18fdfa81b012.png)

**Comment by zeitgeist87** [comment] 2017-02-09 08:39
Thanks for reporting this. This is definitely a bug.

The problem is, that the `greedy` flag is set on the `comment` token. Comments are always highlighted first, so there seems to be no reason for the frag there. I suspect, that it was put there to fix some other issue.

**Comment by zeitgeist87** [comment] 2017-05-08 20:41
This issue should be fixed by #1100

**Closed by zeitgeist87** 2017-05-08 20:41 UTC
