### ISSUE TITLE
Unproper alignment of line numbers

### ISSUE THREAD

**Issue by eakarpov** [PrismJS/prism#1667] opened 2018-12-21 08:05 UTC
Hi! Why when I use a plugin for "line-numbers", in my code block numbers are not aligned as left side relatively with my code in it.

![image](https://user-images.githubusercontent.com/16017789/50331565-229f6d80-0510-11e9-878f-93961611db76.png)

**Comment by RunDevelopment** [comment] 2018-12-21 08:17
Could you please add a description on how to reproduce the bug?
A link to the website or JSFiddle showcasing the bug would be even better.

**Comment by eakarpov** [comment] 2018-12-21 08:41
> Could you please add a description on how to reproduce the bug?
> A link to the website or JSFiddle showcasing the bug would be even better.

I can't properly tune Prism via CDN, so...: https://jsfiddle.net/65ernfb7/
I use the same code in my problem place:
```html
 <pre class="command-line line-numbers" ref="pre">
    <code class="language-cpp" ref="code">
       {{code}}
    </code>
</pre>
```

**Comment by RunDevelopment** [comment] 2018-12-21 13:36
@mAAdhaTTah The problem of spaces between `<pre>` and `<code>` has also caused some problems in the past, I believe. Why not do a kind of preprocessing step to correct that automatically?

**Comment by eakarpov** [comment] 2018-12-21 13:39
> @eakarpov The issue is the indentation. You would need to write it as such:
> 
> ```
>  <pre class="command-line line-numbers" ref="pre"><code class="language-cpp" ref="code">{{code}}</code></pre>
> ```

Hmm.... This fixed the issue... But why is it important? It is rather strange to have necessity of single-lined code-block.

**Comment by RunDevelopment** [comment] 2018-12-21 13:47
It's important because of the way the line number plugin is currently implemented:
The line numbers list you see starts at the `<code>` element and goes down from there as a block. This means that any initial offset (e.g. the indentation of `<code>`) will move the whole line numbers list to the right.

**Comment by mAAdhaTTah** [comment] 2018-12-21 14:18
@RunDevelopment That's what [normalize whitespace](https://prismjs.com/plugins/normalize-whitespace/) does.

@eakarpov Sounds like your issue is resolved, so I'm going to close this, but feel free to ask any follow up questions if you need help.

**Closed by mAAdhaTTah** 2018-12-21 14:18 UTC
