### ISSUE TITLE
groovy transforms &lt; in strings into &lt; instead of into < 

### ISSUE THREAD

**Issue by acerberus** [PrismJS/prism#901] opened 2016-02-19 09:22 UTC
The groovy language highlighter seems to wrongly treat the &lt; html entity when appearing in strings. Consider the following code

`<pre><code class="language-groovy">def a = "&lt;&gt;"</code></pre>`

This should come out as 

`def a = <>`

but instead is transformed into

`def a = &lt;>`

**Comment by zeitgeist87** [comment] 2016-02-19 11:07
I can confirm this bug. It is because of line 40 in `prism-groovy.js`. `env.content` is already HTML-encoded and `Prism.highlight()` encodes it again.

Unfortunately there is no easy solution for this. I think we should remove the `wrap` hook altogether from `groovy` and implement the same functionality with the `inside` property on the `string`-pattern. I'll work on it.

**Comment by zeitgeist87** [comment] 2016-02-19 11:08
@acerberus Thanks for reporting this issue!

**Comment by zeitgeist87** [comment] 2016-02-19 12:40
Should be fixed now.

**Closed by zeitgeist87** 2016-02-19 12:40 UTC
Labels: bug

**Comment by acerberus** [comment] 2016-02-19 13:04
@zeitgeist87 looks good. thanks for the quick fix.
