### ISSUE TITLE
"Paste" from "copy button" going wrong

### ISSUE THREAD

**Issue by worldsdream** [PrismJS/prism#3303] opened 2022-01-21 08:45 UTC
**Information:**
- Prism version: PrismJS 1.26.0
- Plugins: Toolbar and Copy to Clipboard Button
- Environment: Firefox Browser 96.0.1.

!

**Description**
The copy-paste button does not work as expected. The paste will show the numbering in the opposite order. This was always working (been using prismjs for years).

Something clearly changed to the copy button which unfortunately is causing this bug in Firefox. Edge/Chrome is working fine.

**Example**
1. Ensure that you have the latest PrismJS version which is PrismJS 1.26.0.

2. Add some text in the section, for example:

Test1
Test2
Test3

![D9fUDLf1iz](https://user-images.githubusercontent.com/12443285/150494890-b1688508-10b8-45b8-8de9-08b9c35581d8.png)

3. Click the copy button

4. Paste in PowerShell

You can see that it's in a different order!

![tZSZj3u7Jh](https://user-images.githubusercontent.com/12443285/150495043-4112a051-c6e6-4d11-a500-2c18bcf8d4b0.png)

5. Paste in Notepad

You can see that it's in the correct order.

![OpnrjPBoRW](https://user-images.githubusercontent.com/12443285/150495067-7db3a77d-6897-4f22-a468-095ecc28cd26.png)

**Comment by RunDevelopment** [comment] 2022-02-02 12:14
This seems to be a general bug with Firefox's `clipboard.writeText` implementation. I was able to reproduce this bug on a very simple test page.

```html
<!DOCTYPE html>
<html>
<head>
	<title>Document</title>
</head>
<body>
	<button>Click me</button>
	<script>
		document.querySelector("button").addEventListener("click", () => {
			navigator.clipboard.writeText("abc\ndef\nghi\n")
				.then(() => console.log("yay"), () => console.log("oh no"));
		});
	</script>
</body>
</html>
```

The problem seems with FF literally writing the given text to clipboard without accounting for Windows line ends. If the line ends are changed to `\r\n` everything works as expected (as in Chrome).

**Comment by RunDevelopment** [comment] 2022-02-02 12:17
Since this seems like a bug in Firefox to me, I reported it. https://bugzilla.mozilla.org/show_bug.cgi?id=1753202

**Comment by RunDevelopment** [comment] 2022-03-02 11:28
The discussion in the bug report I linked above points to this problem being a spec issue with Clipboard API. Since this has nothing to do with Prism and I don't think that there is a workaround we can do, I'll now close this issue. While problem persists, the fix has to be done by WC3 and Mozilla.

**Closed by RunDevelopment** 2022-03-02 11:28 UTC
Labels: bug, plugins
