### ISSUE TITLE
New Language Request - CFML - ColdFusion

### ISSUE THREAD

**Issue by nastanford** [PrismJS/prism#3575] opened 2022-10-12 03:55 UTC
**Language**
Adobe ColdFusion - cfml

**Additional resources**
[Adobe ColdFusion Docs](https://helpx.adobe.com/coldfusion/cfml-reference/user-guide.html)

I would not mind helping if I have time and can figure out how to help.

**Comment by alangrainger** [comment] 2022-10-12 07:41
If you had simply searched:

![image](https://user-images.githubusercontent.com/16197738/195280530-b7d3da3e-5b79-480e-b016-a401cf3ade1c.png)

You would find:

https://github.com/PrismJS/prism/pull/2771

Which adds partial support for https://github.com/PrismJS/prism/issues/2035 , which is an already existing request for ColdFusion.

So you might find your issue is already solved in https://github.com/PrismJS/prism/pull/2771 , but if not, at least it's a good base to start from.

**Comment by RunDevelopment** [comment] 2022-10-12 12:19
Duplicate of #2035.

**Closed by RunDevelopment** 2022-10-12 12:19 UTC
Labels: duplicate, language-definitions, new language
