### ISSUE TITLE
Highlighted code line is not position correctly if zoomed in/out of browser window

### ISSUE THREAD

**Issue by orangecoding** [PrismJS/prism#1154] opened 2017-07-05 14:03 UTC
Steps to reproduce:
- Have a code view where you need to scroll
- highlight a line of code that is not in view (means you need to scroll to this line)
- scroll to this line and then use Cmd + to zoom into the browser window (works with zooming out as well)

You will see that the highlight is not on the correct line anymore.

Here's a complete test case:
http://jsbin.com/pumiruquri/edit?html,css,output

Open the testcase scroll to the highlighted line and zoom into the view.

**Comment by Golmote** [comment] 2018-02-17 11:07
Hi! Thanks for reporting! I can't reproduce the issue anymore on your example. Can you confirm it appears to be fixed?

**Comment by Golmote** [comment] 2018-04-05 17:32
Closing this issue, since it does not seem to exist anymore.

**Closed by Golmote** 2018-04-05 17:32 UTC
