### ISSUE TITLE
Language request:cshtml

### ISSUE THREAD

**Issue by WuHaaaaa** [PrismJS/prism#2187] opened 2020-01-17 05:03 UTC
**Language**
A short description of the language.
It is a language in asp.net mvc, also known as razor, detailed address: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1
**Additional resources**
E.g. The official website, documentation or language specification.
detailed address: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1

Thank you for everything ：)

**Comment by RunDevelopment** [comment] 2020-01-17 11:49
Duplicate of #1225.

**Closed by RunDevelopment** 2020-01-17 11:49 UTC
Labels: duplicate, language-definitions, new language
