### ISSUE TITLE
error with webpack5

### ISSUE THREAD

**Issue by XinChou16** [PrismJS/prism#3745] opened 2023-10-27 07:24 UTC
pattern: /=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+)/,

compiler error in webpack5

**Comment by gethari** [comment] 2023-10-27 07:33
+1 facing this issue out of a blue moon on a no change project since yesterday

**Comment by mAAdhaTTah** [comment] 2023-10-27 16:45
First, I would need a minimal reproduction to investigate this.

Second, this almost certainly isn't on Prism as this code hasn't changed in a while, so there's probably a bug in Webpack itself or a loader you're using.

**Comment by mAAdhaTTah** [comment] 2023-10-27 16:46
Could be this: https://github.com/webpack/webpack/issues/17769

**Comment by mAAdhaTTah** [comment] 2023-10-27 16:56
Closing this as as Webpack (specifically Acorn) issue. Follow the suggestion in the linked description.

**Closed by mAAdhaTTah** 2023-10-27 16:56 UTC
