### ISSUE TITLE
Javascript Hightlighting: Match-brace is not working properly with Template String Placeholder

### ISSUE THREAD

**Issue by KotoriK** [PrismJS/prism#2540] opened 2020-09-06 09:26 UTC
**Information**
- Language: [Javascript (and its variant, TypeScript,etc.)]
- Plugins: [match-braces]
- Bug can be reproduced on Prism.js Version:>=v1.20

**Description**
As the title said.
Match-brace will be confused when meeting placeholders (like ${js_expression}) in Template literals. It will match the brace of the placeholder with a former brace.

**Code snippet**

<details>
<summary>The code being highlighted incorrectly.</summary>

```javascript
const func =(a,b)=>{
return `${a}:${b}`//match-brace will match the first right-brace in the first placeholder with the former left-brace 
//and the left-brace of the first placeholder might be left unmatched
}
```

</details>

**Comment by KotoriK** [comment] 2020-09-06 09:31
this issue #2536 might be describing a same problem.

**Comment by RunDevelopment** [comment] 2020-09-06 11:04
Yeah, I see the problem. Match braces (MB) basically just guesses bracket pairs. Prism doesn't tag opening/closing brackets, so MB has a list of known brackets. Any punctuation token of a known bracket will be labeled as opening or closing. MB then tries to pair up all labeled punctuation tokens.

The problem is that MB knows `{`, `}` but not `${`. We could make `${` as "alias" for `{`, so MB treats them the same but this doesn't generalize well for other languages.

The proper solution here is to change the language definitions to properly label opening/closing punction themselves (instead of MB having to guess) but this requires changing >200 languages definitions...

I'll implement the aliasing for now. A fix will be up soon.

> this issue #2536 might be describing the same problem.

That makes sense. #2536 has no description, so let's keep this issue and close #2536.

**Closed** 2020-09-22 14:50 UTC
Labels: bug, language-definitions, plugins
