### ISSUE TITLE
[PHP] opening and closing `"` and `'` strings are also interpreted when already part of a string.

### ISSUE THREAD

**Issue by Danon** [PrismJS/prism#2297] opened 2020-04-08 18:05 UTC
**Information:**
- Prism version: 1.20
- Plugins: `prism-react-renderer`, altough I don't know if that counts as "plugin"
- Environment: Webpack, docusaurus framework

**Description**
When using language PHP, opening and closing `"` and `'` strings are also interpreted when already part of a string.

**Example**
 - Open: https://prismjs.com/test.html#language=php
 - Paste: 
   ```php
   <?php 
   $variable = ["I'm", '19', 'years', 'old'];
   ```

I interpret it as:
```
           ↓ closing quote
   ↓ opening quote
["I'm", '19', 'years', 'old'];
 ↑ opening double-quote
        ↑ closing double-quote
```
Which is obviously incorrect. The first `'` shouldn't be treated as an opening quote, since it's already in a string.

**Comment by RunDevelopment** [comment] 2020-04-08 18:12
I will close this as a duplicate of #1431 because they are both caused by #1492.

The fix is currently in development.

**Closed by RunDevelopment** 2020-04-08 18:12 UTC
