### ISSUE TITLE
Getting element height in lineNumbers plugin

### ISSUE THREAD

**Issue by mortalis13** [PrismJS/prism#560] opened 2015-03-30 09:01 UTC
Hi.
I try to edit the lineNumbers plugin so it shows right numbers when the `<pre>` has text wrapping.
I wrapped each code line in a `div` to get its height and then adjust line numbers `span`'s heights.
So the problem is when I get a **line height** with this code    
    
    var codeLineHeight=document.getElementsByClassName('code-line')[0].clientHeight
before the following line in the `after-highlight` hook within the **lineNumbers** plugin part of code  

      env.element.appendChild(lineNumbersWrapper);
  
the line numbers container (`<span class="line-numbers-rows">`) shifts down.  
<img src="http://s27.postimg.org/545ax5wub/prism_problem.png">  
I mean if I place the height request after **that line** all works.

This happens with all **size** and **coordinate** properties and with `getComputedStyle` method:
<pre>
clientHeight
clientWidth
clientLeft
clientTop

offsetHeight
...

scrollHeight
...

</pre>

What can be done with it?

Thanks.

**Comment by Golmote** [comment] 2015-03-30 17:06
Hi,

Could you give a link to some gist or anything so that I can test your actual code?

**Comment by mortalis13** [comment] 2015-03-30 18:51
Sorry for disturbance.
I already solved this problem.

_Sometimes it's useful to write down your problem somewhere. It helps to think and find a solution faster then when kiping it i mind..._

I wrapped each line in a `div` but the `line-numbers-rows` `span` is `block` styled. That's why they conflicted. I've set `float:right` to the code section and the two parts were aligned right.  

Just strange that if I don't get any size properties before the line numbers are added to the `<pre>` block the alignment doesn't smash. And if, for example, I uncheck/check the `position` property in **Firefox Inspetor** the gutter goes to the right place.

...

But after these experiments I found that if I select the code in these `div`-lines on the page and then paste it in a text editor the spaces don't save and the code indentation becomes completely broken.

So I left the code to be in native `span`'s (without `div`'s around the lines). But only used a "`div`'ved" simulation in the `prism.js` code to get the right line heights. Then used these heights to set `line-numbers-rows` `span`'s heights.

So now the code produces acceptable results for me.
![prism-wrap](https://cloud.githubusercontent.com/assets/10464927/6903571/d0be0b34-d723-11e4-8a96-a961c9ffbda5.png)

If you can please look at the [repository](https://github.com/mortalis13/Prism-Wrap-Lines) I've created. It contains files I edited and runs from a local place. I marked my changes in `prism.js` and `prism.css` files as  

<pre>
/* ---add--- */
    ...
/* ---add_end--- */
</pre>

Maybe my `floats` isn't the right way to solve the alignment...
Could you say something about it?

Thanks.

**Comment by Golmote** [comment] 2015-03-31 06:26
I played around with the idea for a while, and I perfectly understand all the problems you faced! The fact than spaces are discarded when copy-pasted from inside a block element is a real pain in the neck!

I also reproduced the problem with the position of the `.line-numbers-rows` span, but this appears to be some glitch to me, since if the browser rerenders the element for some reason, it goes in the right place.
So well... I found out that forcing the rerender of the `code` block at the end of the code actually fixes the problem in Firefox:

```javascript
  env.element.appendChild(lineNumbersWrapper);

  // Force browser to rerender the element
  env.element.style.display = 'none';
  env.element.offsetHeight;
  env.element.style.display = '';

});
```

But yes, I know, this is an ugly hack.

**Comment by mortalis13** [comment] 2015-03-31 07:56
OK, thanks man.
I tried the similar part

    env.element.style.display = 'none';
    env.element.style.display = 'block';
and with `position` but without getting the size.

**Comment by Golmote** [comment] 2015-03-31 10:11
If I remember correctly, getting the size is actually what "invalidates" the current rendering and forces the browser to render it again. ;)

**Comment by Golmote** [comment] 2015-04-01 06:20
I consider this problem solved, so I'm closing the issue.

**Closed by Golmote** 2015-04-01 06:20 UTC
