### ISSUE TITLE
Prism seems to work but I can not copy the code

### ISSUE THREAD

**Issue by MaxCCC** [PrismJS/prism#1282] opened 2018-02-05 18:34 UTC
I'm injecting prismjs in my Ghost blog. 

Blog header:
```
<link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.10.0/themes/prism-okaidia.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.10.0/plugins/line-numbers/prism-line-numbers.min.css" rel="stylesheet" />
```

Blog footer:
```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.10.0/prism.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.10.0/plugins/line-numbers/prism-line-numbers.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.10.0/components/prism-csharp.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.10.0/components/prism-php.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.10.0/components/prism-bash.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.10.0/components/prism-yaml.min.js" ></script>
```

The prism is highlighting and the colors are fine. But the problem is I can not copy the code. It seems to be like an image. It's in every browser. I'm using this [theme](https://github.com/lvthillo/velox).

**Comment by mAAdhaTTah** [comment] 2018-02-05 18:38
Do you have a live example we can look at?

**Comment by MaxCCC** [comment] 2018-02-05 18:51
@mAAdhaTTah Well, I found this example (same theme): https://dreyacosta.com/functional-javascript/

**Comment by Golmote** [comment] 2018-02-05 19:07
I think the issue is caused somehow by this rule in the CSS.

![8b0gswu](https://user-images.githubusercontent.com/565460/35823528-1e7b8cb2-0ab0-11e8-9c89-4cb275d19848.png)

**Comment by mAAdhaTTah** [comment] 2018-02-05 19:12
@Golmote Yeah, if I disable that in devtools, the issue goes away. Gonna have to look up the `::selection` selector now, first time I've seen that :D.

**Comment by MaxCCC** [comment] 2018-02-05 19:20
@Golmote @mAAdhaTTah Thanks, so this means it will be fixed in a next version of prismjs? 1.11.1 already or not? Thanks for the replies.

**Comment by Golmote** [comment] 2018-02-05 19:21
It behaves as if setting `::(moz-)selection` (at all, even with no styles defined) entirely replaced the default styles.
@MaxCCC No it won't be fixed in Prism, because AFAICT, this is not a Prism bug. The default theme is Prism [applies a background on the selection](https://github.com/PrismJS/prism/blob/gh-pages/themes/prism.css#L33) so the issue does not occur by default.

I think you should create an issue in the [Velox](https://github.com/lvthillo/velox) repo.

**Comment by MaxCCC** [comment] 2018-02-05 19:23
@Golmote @mAAdhaTTah Okay, thanks for the info. You can close this.

**Closed** 2018-02-05 19:23 UTC
