### ISSUE TITLE
Prismjs is not working when you use tab i.e angular material tab or any plain tabs

### ISSUE THREAD

**Issue by itvilla-co-in** [PrismJS/prism#2838] opened 2021-03-27 10:17 UTC
when you create multiple tabs it works fine in the first tab but any tab after the first one it does not higlight the code nor gives the styling.

**Comment by RunDevelopment** [comment] 2021-03-27 13:24
Please provide more information.

All the information you have provided is:

- There is some problem with Prism for you.
- You use Angular.
- Something with tabs (no idea what that is about).

This is not enough. To understand your problem, I need to know a few things. This includes but is not limited to: 

- Your Prism version
- The selected languages/plugins/themes
- Your environment (browser/node/webpack/...)
- How you import Prism (require/import/script tags)
- How your code is using Prism (automatic highlighting/manual)

We have issue templates that ask for these things because we need to know these things. There are many possible reasons as to why Prism is not working for you. To help you, I have to find out the cause of your problem and I need information to do that.

The easiest way to answer all questions is to provide a **reproducible example**. I won't have to ask questions if I can see the problem for myself. A reproducible example can be anything from a link to a non-working website, the actual source code of your application, or a small example project that shows the bug in action. It just has to be something I can run on my computer.

I will close this issue now because of insufficient information. If it is an actual bug, I'll reopen it.

We can still talk. Just comment the information I asked for below and then I can help you.

**Closed by RunDevelopment** 2021-03-27 13:24 UTC
