### ISSUE TITLE
Svelte/SvelteKit

### ISSUE THREAD

**Issue by shinokada** [PrismJS/prism#3321] opened 2022-02-05 22:26 UTC
**Language**
Svelte is a [free and open-source](https://www.wikiwand.com/en/Free_and_open-source) [front end](https://www.wikiwand.com/en/Front_end_and_back_end) compiler[[4]](https://www.wikiwand.com/en/Svelte#citenote4) created by Rich Harris.
[Svelte](https://svelte.dev/)

**Additional resources**
E.g. The official website, documentation or language specification.
[Svelte Doc](https://svelte.dev/docs)
[SvelteKit Doc](https://kit.svelte.dev/docs)

**Comment by hoonweiting** [comment] 2022-03-14 15:50
Just noticed that this is a duplicate of #2090, although I'm not sure if SvelteKit is covered. Someone wrote an extension for Svelte though: https://github.com/pngwn/prism-svelte, maybe you'll be interested!

**Comment by RunDevelopment** [comment] 2022-03-14 16:08
SvelteKit adds new concepts, but it doesn't to add any new syntax. So this issue is indeed a duplicate of #2090. Thank you for pointing that out @hoonweiting!

**Closed by RunDevelopment** 2022-03-14 16:08 UTC
Labels: language-definitions, new language
