### ISSUE TITLE
JS syntax highlighting issue with a string containing /* followed by single line comments

### ISSUE THREAD

**Issue by loreanvictor** [PrismJS/prism#2394] opened 2020-05-19 07:52 UTC
**Information:**
- Prism version: 1.20.0
- Environment: Browser, Node, Webpack

**Description**
In a Javascript code snippet, if a string containing `/*` is followed by two (or more) single-line comments, only the first single line comment is recognized as a comment. The issue does
not exist with multi-line comments or strings not containing `/*`.

**Example**
https://stackblitz.com/edit/prismjs-bug

**Comment by RunDevelopment** [comment] 2020-05-19 14:01
This is caused by #1492.

**Comment by RunDevelopment** [comment] 2020-07-13 11:27
Fixed by #2032.

**Closed by RunDevelopment** 2020-07-13 11:27 UTC
Labels: bug
