### ISSUE TITLE
Code overflow line numbers

### ISSUE THREAD

**Issue by johnsmeeth** [PrismJS/prism#933] opened 2016-04-17 18:20 UTC
Hello everyone.
I just download prismjs with line-numbers plugin but when i use, my code overflow line numbers look ugly. Please tell me how to fix.
Many thanks.
Image i captured 
![prismjs_error](https://cloud.githubusercontent.com/assets/5707587/14589086/b919cb9e-0503-11e6-9c44-afa8e0cf7737.png)

**Comment by LeaVerou** [comment] 2016-04-19 04:40
Which plugins are you using? Is there an online example we could look at?

PS: "Hello sir" is needlessly specific. Not all of us working on this project are men.

**Comment by mAAdhaTTah** [comment] 2018-05-26 22:55
@johnsmeeth If you can provide a reproducible test case, feel free to reopen and we'd be happy to take a look and see if we can resolve it, but since it's been a while, I'm going to close this.

**Closed by mAAdhaTTah** 2018-05-26 22:55 UTC
