### ISSUE TITLE
Blogger mode

### ISSUE THREAD

**Issue by VahidN** [PrismJS/prism#915] opened 2016-03-21 09:51 UTC
Blogger adds `<br/>` instead of `\n` to posted codes automatically. It needs this fix to work:

``` javascript
/** Blogger mode flag. */
bloggerMode : false,

var br = /<br\s*\/?>/gi;    
if (config.bloggerMode == true){
    str = str.replace(br, '\n');
}

```

It's taken from `alexgorbatchev.com/SyntaxHighlighter`.

**Comment by Golmote** [comment] 2018-03-04 11:46
I'll close this issue as a duplicate of #832. Hopefully the same solutions apply.

**Closed by Golmote** 2018-03-04 11:46 UTC
Labels: duplicate
