### ISSUE TITLE
Problems with several code blocks in the same page

### ISSUE THREAD

**Issue by BartolomeSintes** [PrismJS/prism#3363] opened 2022-03-03 13:34 UTC
**Information:**
- Prism version: 1.27 downloaded from prismjs.com
- Plugins: Copy to Clipboard + Toolbar (and also Command line, Line numbers, Show invisibles and Keep markup)
- Environment: Browser

**Description**
I have updated prism.js from version 1.25 into 1.27 (with Copy to Clipboard plugin) and prism does not work properly now.
The html source code of my pages is like this:
```
<div class="codigo">
        <pre>
<code class="language-python">import webbrowser
```

If I use the prism version 1.25 I downloaded last September, this code is shown in the Firefox code inspector like this:
```
<div class="codigo">
    <div class="code-toolbar">
        <pre class="language-python" tabindex="0">
<code class="language-python">import webbrowser
```

But if I use prism version 1.27, this code is shown in the Firefox code inspector like this:
```
<div class="codigo">
    <div class="code-toolbar">
        <pre class="language-none" tabindex="0">
<code class="language-python language-none">import webbrowser
```

I you need aditional information or file samples, please ask for them and I would provide them the best I can.

Thanking you in advance,
Bartolome Sintes

**Comment by RunDevelopment** [comment] 2022-03-03 13:37
Could you please provide a minimal example project reproducing your problem?

**Comment by RunDevelopment** [comment] 2022-03-04 11:05
I see the problem:

![image](https://user-images.githubusercontent.com/20878432/156751319-9cffdc20-b7aa-4688-8968-62ca44c33da0.png)

The problem is `copy-language-python`. The old regex (used in v1.25.0) incorrectly detects this class as a `language-xxxx` class. This bug was fixed in #3167.

The real problem is that Prism tries to highlight that code block in the first place. This is because the [CSS selector we use](https://github.com/PrismJS/prism/blob/499b1fa0c6c2bb10cf9dd4cf9e530578e7360dd1/components/prism-core.js#L520) works on substrings and not CSS classes. That's a bug. I'll file a separate issue for this.

Does this explain your problem?

**Comment by BartolomeSintes** [comment] 2022-03-07 13:08
Yes, thank you very much for your explanation.
I was using two versions of prism.js, one with the copy-to-clipboard plugin and another one without it. I have realised now that it just worked by chance. I can get the same result using only the version with the plugin and adding a class when I would want to hide the toolbar.

**Comment by RunDevelopment** [comment] 2022-03-07 13:18
Glad to see that your issue has been resolved!

> I can get the same result using only the version with the plugin and adding a class when I would want to hide the toolbar.

Yes. Pretty much all plugins have a way to turn them off for specific code blocks.

**Closed by RunDevelopment** 2022-03-07 13:18 UTC
