### ISSUE TITLE
SAS Language improvements

### ISSUE THREAD

**Issue by cedporter** [PrismJS/prism#1954] opened 2019-06-28 14:17 UTC
**Information**
- Language: SAS

**Description**
I'd like to make some substantial improvements to the SAS language support. I've got a [draft commit](https://github.com/cedporter/prism/blob/sas-improvements/components/prism-sas.js) ready, but I'm having trouble with the "rest:" option. I can always leave it out for now, but if someone could give me some help here, I hope to get that working, add a test for it, and get a pull request in for the changes I've made.

**Code snippet**

<details>
<summary>My intention here is to capture "PROC SQL;" followed by any text up to and including the next "PROC \w", "QUIT", "RUN" or "DATA". The code that follows is what I have thus far. It does capture the text as expected, but it does not apply SQL syntax highlighting to the text after the "step".</summary>

```
	 'procSQL': {
	 	pattern: /(^|\n)(?:proc\s+sql);[\s\S]+?(?:\r?\n|\r)(?:proc\s\w+|quit|run|data(?!\=));/im,
	 	alias: 'string',
	 	inside: {
			'step': {
				pattern: /(^|\n)(?:proc\s+sql)/i,
				alias: 'keyword'
			},
	 		rest: Prism.languages.sql
	// 	}
	 },
```
</details>

**Comment by RunDevelopment** [comment] 2019-06-28 17:58
@cedporter The problem isn't `rest` but `Prism.languages.sql`. Prism always tries to load as few languages as possible, so `Prism.languages.sql` is simply undefined.
You need to add a dependency for SQL in [`components.json`](https://github.com/cedporter/prism/blob/fa84427d5f100042d938eca99a5a9e7e96bbeca8/components.json#L775) using `require` (similar to how SASS requires CSS below). This should solve your problem.

**Comment by RunDevelopment** [comment] 2019-09-01 19:47
#1981 is merged already.

**Closed** 2019-09-01 19:46 UTC
Labels: language-definitions
