### ISSUE TITLE
Add support for Blade (Laravel)

### ISSUE THREAD

**Issue by reineltchris** [PrismJS/prism#2621] opened 2020-11-06 06:41 UTC
I can't find any code highlighter or editor wich has support for laravel blade.
It would be really nice if PrimJs had support for it.. Im searching for months now.

**Comment by RunDevelopment** [comment] 2020-11-06 18:05
Duplicate of #2403.

---

Also, Blade is tricky to implement. I don't think that we will support it any time soon. Sorry.

**Closed by RunDevelopment** 2020-11-06 18:05 UTC
Labels: enhancement

**Comment by nicodevs** [comment] 2025-07-15 01:20
If you still need a Blade language definition for Prism.js, I published this package:

https://github.com/nicodevs/prism-blade

Site: https://nicodevs.github.io/prism-blade
