### ISSUE TITLE
show-language conflicts with line-numbers

### ISSUE THREAD

**Issue by dylanmackenzie** [PrismJS/prism#569] opened 2015-04-16 19:53 UTC
The show-language plugin sets `overflow: auto` on the `code` element. This causes the line numbers (which are bumped outside of the code element with a negative margin) to become invisible. The offending line is [here](https://github.com/PrismJS/prism/blob/gh-pages/plugins/show-language/prism-show-language.css#L4-5). I don't know why show-language needs `overflow: auto`: removing it fixes the problem<s>, but I'm sure there are edge cases I'm not considering</s>. Scrolling is supposed to happen on the `pre` element anyways, so this can be removed safely. I'll open a pull request.

**Comment by Golmote** [comment] 2015-04-17 17:09
@dylanmackenzie  Can you confirm the problem is fixed, now #571 has been merged?

**Comment by dylanmackenzie** [comment] 2015-04-18 01:09
Yup, the line numbers look good now. Obviously the tag does not stay in view when scrolling anymore. Out of curiosity, would wrapping the pre element with a div when the plugin is loading be worth considering? I can't think of any other way to get that scrolling behavior without messing with prism core. It seems like a pretty inelegant solution though.

**Comment by Golmote** [comment] 2015-04-18 07:18
This could solve several issues, indeed. This could even not be limited to this plugin. But this would be a breaking change regarding the global markup of the `<pre>` elements.

**Closed** 2015-04-18 07:19 UTC
