### ISSUE TITLE
JSX - Nested objects inside props

### ISSUE THREAD

**Issue by kevinalexandermanson** [PrismJS/prism#2598] opened 2020-10-20 21:42 UTC
**Information**
- Language: JSX
- Plugins: None

**Description**
Nested objects inside attributes/props in JSX seems to break the syntax highlighting. Based on reading some other issues it seems like maybe this is not something that would be supported, but thought I would just confirm that this is the case.

**Code snippet**

<details>
<summary>The code being highlighted incorrectly.
</summary>

```
<Component one={{ two: { three: {} } }} />
```

</details>

**Screenshot**

![image](https://user-images.githubusercontent.com/27664726/96647179-b69b2400-1389-11eb-9934-76a7dce39dd7.png)

**Expected (without the 3rd level of nesting)**
![image](https://user-images.githubusercontent.com/27664726/96647290-d92d3d00-1389-11eb-93ec-a78674efba09.png)

**Comment by RunDevelopment** [comment] 2020-10-22 15:04
This is one of the core limitations of Prism being a regex-based: we can't do nested structures. We usually work around this by supporting some number of levels of nestedness but it seems like you found out how many levels we support ;).

Unfortunately, this isn't something we can (easily) fix. 

We already have a similar issue, so I'll close this as a duplicate.

Duplicate of #1548

**Closed by RunDevelopment** 2020-10-22 15:04 UTC
Labels: language-definitions
