### ISSUE TITLE
@* *@ comment support for asp-net

### ISSUE THREAD

**Issue by CoenraadS** [PrismJS/prism#1419] opened 2018-05-07 07:07 UTC
Hello

I was using the `markup+javascript+csharp+aspnet` on an asp-net razor file, and noticed that razor multi-line comments arn't supported.

```
        @*<script>
            $(document).ready(function () {
                if(@Model.ExperimentOptions)
             document.getElementById("gomap").click();
            })
        </script>*@
```

**Comment by Golmote** [comment] 2018-05-10 09:55
Hi @CoenraadS and thanks for reporting.

I'm not familiar at all with Razor, but I don't think we have support for it at the moment, since issue #1225 asks for it. If the syntax in your example is not pure ASP.NET, I guess it makes sense it's not highlighted at this time.

Please close this issue if this is indeed a duplicate of #1225. Otherwise, can you tell me more about this (maybe a link to some documentation)?

**Closed** 2018-05-10 10:54 UTC
Labels: enhancement, language-definitions
