### ISSUE TITLE
Operators get a background highlight

### ISSUE THREAD

**Issue by bennettzug** [PrismJS/prism#3841] opened 2024-10-30 20:09 UTC
**Description**
Throughout the web, I occasionally see operators highlighted a slightly different shade than the background color, which looks very strange. (I've filed bug reports through various companies due to this) I've seen this all over but I think I've now tracked it down to being from Prism.

**Example**

Here's an example on your website (the line `|x| x + 1i;`), from
https://prismjs.com/known-failures.html
<img width="427" alt="image" src="https://github.com/user-attachments/assets/d79c4d97-d488-4ee7-b8e6-cb4846907b51">

**Comment by Golmote** [comment] 2024-10-30 21:54
Hello,

This is intentionnal, it's part of the theme. https://github.com/PrismJS/prism/blob/b58cd7227fec6c7ce312d87d24919ec109a0b7fd/themes/prism.css#L109-L110

Duplicate of https://github.com/PrismJS/prism/issues/3274, https://github.com/PrismJS/prism/issues/1347, https://github.com/PrismJS/prism/issues/1691.

**Closed by Golmote** 2024-10-30 21:54 UTC

**Comment by dhust** [comment] 2025-01-27 19:51
I wish this wasn't the case. I've spent hours trying to get rid of it.
