### ISSUE TITLE
Highligt works just on my first code block when using a <pre> wrapper

### ISSUE THREAD

**Issue by fatalerrortan** [PrismJS/prism#1193] opened 2017-09-23 00:00 UTC
Thanks for considering my request in advance :)
```
<div class="language-php">
  <pre>
    <code class='line-numbers'>
          <?php 
               .................Block A.............     Highlighter and line number for A works fine : )
           ?>
    </code>
 </pre>

<pre>
    <code class='line-numbers'>
          <?php 
               .................Block B.............  Highlighter and line number for B Never works
               // It works only without <pre>.  But I can't use line number anymore
           ?>
    </code>
 </pre>
</div>
```
Online example: https://www.xulin-tan.de/post/19   => only the first code block is rendered with highlighter.  the other 2 code blocks use the same prismjs syntax like the first one, but never work

**Comment by Golmote** [comment] 2017-09-23 00:11
Hi! Please provide an online example reproducing this issue.

**Comment by it-community** [comment] 2017-10-03 22:52
Hello I have the same workarround

The issue is not on firefox, but only on chrome or opera.

Example :
https://www.sysadmin-community.com/remove-a-host-from-backuppc/

On firefox https://www.xulin-tan.de/post/19 => no problem
On chrome/opera https://www.xulin-tan.de/post/19 => only first code OK

Best Regards

**Comment by it-community** [comment] 2017-10-03 22:53
May be link to issue #1181

**Comment by mAAdhaTTah** [comment] 2017-10-13 02:16
Ugh, yeah, this is #1181. This is painful...

**Comment by Golmote** [comment] 2017-10-19 18:24
Should be good now that #1206 is merged.

**Closed by Golmote** 2017-10-19 18:24 UTC
