### ISSUE TITLE
Diff Highlight plugin is breaking in Safari

### ISSUE THREAD

**Issue by jlengstorf** [PrismJS/prism#2279] opened 2020-03-30 16:21 UTC
**Information:**
- Prism version: 1.19.0
- Plugins: line-highlight+diff-highlight
- Environment: browser

(custom build using: https://prismjs.com/download.html#themes=prism&languages=markup+css+clike+javascript+bash+diff+git+go+graphql+json+markdown+jsx+ruby+toml+yaml&plugins=line-highlight+diff-highlight)

**Description**

In Safari, the regex replacement in the Diff Highlight plugin seems to be replacing the code with `/span>` and other malformed HTML

![n6sy86A_d](https://user-images.githubusercontent.com/163561/77936353-a2fe6380-7267-11ea-83a7-f662b5f1ef3f.jpg)

This happens on both mobile and desktop Safari.

**Example**

See the diffs in this article: https://www.netlify.com/blog/2020/03/23/migrate-your-wordpress-site-to-the-jamstack/#install-and-configure-gatsby-source-graphql

**Comment by RunDevelopment** [comment] 2020-03-30 17:15
Duplicate of #2238.

The fix is already in master and a new version will be released in the next couple of days.

**Closed by RunDevelopment** 2020-03-30 17:15 UTC

**Comment by jlengstorf** [comment] 2020-03-30 20:02
@RunDevelopment that will work right now, or once the new version is released?

**Comment by jlengstorf** [comment] 2020-03-30 20:02
(also thank you for the quick reply! I really appreciate it!)

**Comment by RunDevelopment** [comment] 2020-03-30 20:12
If you're using the [download page](https://prismjs.com/download.html) to build Prism, it will work right now.
