### ISSUE TITLE
A CSS/base64 sample hung Safari/Mac

### ISSUE THREAD

**Issue by murtaugh** [PrismJS/prism#77] opened 2013-03-14 18:23 UTC
Probably not totally unexpected, but this code sample:

    <pre><code class="language-css">#nav li:after {
        content:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAI0lEQVQIW24//8/w8yZM//DMIjPAGPAMIiPWxCIMQQxzAQAoFpF7lGFr24AAAAASUVORK5CYII=);
    }</code></pre>

… caused the Safari Web Content process to freak out. Removing the class eliminated the issue.

**Comment by loganfranken** [comment] 2015-06-20 04:12
Hey @Golmote, I think this can be closed (unless you had a live example you wanted us to dig into a little further, @murtaugh?)

**Comment by Golmote** [comment] 2015-06-20 10:47
@loganfranken: I think Prism still have issues with some long patterns, but since the issue described here is so specific I think we could close it, indeed. But before doing so, I'd like to hear @LeaVerou's opinion about this.

**Comment by loganfranken** [comment] 2015-06-28 00:29
@Golmote Did you want to still keep this one open?

**Comment by Golmote** [comment] 2015-06-28 00:45
@LeaVerou Feel free to reopen this issue if you think we should investigate further. For now, the issue cannot be reproduced, so I'm closing it.

**Closed by Golmote** 2015-06-28 00:45 UTC
