### ISSUE TITLE
line highlight error in Chromium (Webkit?)

### ISSUE THREAD

**Issue by poifox** [PrismJS/prism#51] opened 2012-11-08 02:54 UTC
Got some trouble with the absolute positioning in Chromium and Opera for Ubuntu Linux.

The code is styled correctly and looks [like this](http://poifox.com/tmp/prism/prism.js.png). But then for the syntax highlighting looks [like this](http://poifox.com/tmp/prism/prism.js_err.png), as you can see the Highlight area is inserted as supposed but it clear itself. The theme is not modified from what the site provides.

I tried this also without any of my site's styles and the problem persists, even with the default theme; so I'm forced to conclude it may be a bug in the prism theme styles or a style clash with Chromium/Webkit/Opera maybe? the problem does not appear in Firefox.

My build includes only the line highlight plugin and excludes Java syntax.

Help to solve or work-around this is most appreciated.

Thanks!

__[Update]__ I just found out that `div.line-highlight` element is not given the style attribute in Chromium and Opera. So that kindof points to the JS part of Prism.

**Comment by loganfranken** [comment] 2015-06-20 03:20
Hey @poifox!

I know it's been a long while, but is this still happening for you? (Your images no longer work)

Line highlighting works for me in both the latest Chrome and Opera, so I imagine this is now fixed unless you say otherwise.

**Comment by poifox** [comment] 2015-06-27 19:05
@loganfranken IDK, I stopped using the lib shortly after reporting this bug, I may start using it soon on my personal site, I'll let you know if I notice anything.

**Comment by loganfranken** [comment] 2015-06-28 00:11
Sounds good, @poifox!

I can't reproduce this on my end and it sounds like it might be a bit before you can test, so how would you feel about closing this for now and reopening if it pops up for you again?

**Comment by loganfranken** [comment] 2015-07-05 00:45
I think this can be closed! (Unless you are able to reproduce it, @poifox?)

**Comment by Golmote** [comment] 2015-07-11 08:28
As it cannot be reproduced, I'm closing this issue.

**Closed by Golmote** 2015-07-11 08:28 UTC
