### ISSUE TITLE
Lang undefined in extend.

### ISSUE THREAD

**Issue by AtomicNicos** [PrismJS/prism#3477] opened 2022-06-16 10:58 UTC
**Information:**
- Prism version: 1.24.0
- Plugins: none
- Environment: Browser (Firefox), Angular 14.0

**Description**
When using the latest version via marked, PrismJS throws `Uncaught TypeError: lang is undefined` at line 345 of `prism.js`.

![image](https://user-images.githubusercontent.com/18284503/174053098-06680f5e-5d4f-4b09-8093-96313504d807.png)

This is due to the fact that `_.languages` does not contain all the languages that Prism supports, namely `C` and `C++`.

![image](https://user-images.githubusercontent.com/18284503/174055112-cf0f5de1-a66b-4f24-9647-937df717d8f8.png)

From the code, we see 1 thing: that the `lang` variable doesn't have to be defined, just overwritten *if* it exists. If it doesn't, `lang` becomes `undefined` whereas we could render the value safe by adding an empty object as a catch value, not affecting the behavior of the for loop, like below:

```js
// prism.js:341
			extend: function (id, redef) {
				var lang = _.util.clone(_.languages[id]) ?? {};

				for (var key in redef) {
					lang[key] = redef[key];
				}

				return lang;
			},
```

With the above, the code runs without errors.

**Comment by RunDevelopment** [comment] 2022-06-16 12:03
> With the above, the code runs without errors.

And it silently does the wrong thing.

The problem is not that `lang` is `undefined` by why it is `undefined`. [C++ extends C](https://github.com/PrismJS/prism/blob/9a4e725b76d22759fec58e1929450bbfe1bb6661/components/prism-cpp.js#L6), so C is required in order for C++ to function correctly. So the problem is that C isn't loaded (yet) when C++ is loaded. This be because they are loaded in the wrong order, or because C isn't loaded at all.

This problem has to be fixed by whoever is loading the languages. Unfortunately, loading languages is currently one of the ugliest parts of Prism and relatively easy to get wrong. Depending on your runtime environment, you should use either [`loadLanguages`](https://prismjs.com/#basic-usage-node), our [babel plugin](https://prismjs.com/#basic-usage-bundlers), [Auto Loader](https://prismjs.com/#basic-usage-cdn), or a bundle from our [download page](https://prismjs.com/download.html).

**Closed by RunDevelopment** 2022-06-16 12:03 UTC
