### ISSUE TITLE
Making list of Bash functions extensible

### ISSUE THREAD

**Issue by dhruvkb** [PrismJS/prism#3361] opened 2022-03-01 20:49 UTC
**Motivation**

The Bash language definition has a hardcoded list of functions.
https://github.com/PrismJS/prism/blob/b53832cd1c4e1dcc106cf3b46258bcc5c063e98e/components/prism-bash.js#L163

This approach has a major downside that it can never encompass the full range of commands. If we try to be as accommodating as possible the list will grow endlessly. If we try to restrict it, we need to define the criteria which decides which command to add and provide some way for users to extend it in userland.

I encountered this issue because
- `npm install abc` treats both `npm` and `install` as functions.
- `poetry add abc` does not recognise `poetry` as a function.

This rigidity makes the syntax highlighting very erratic for my usecase.

**Description**
I propose that we should be able to specify a custom list of functions that are added/removed from the list of pre-defined ones (or some way to replace the list of functions entirely), not sure what the ideal API to do this would be.

**Comment by RunDevelopment** [comment] 2022-03-02 11:23
The problem is that have to rely on a list in the first place. Literally any sequence of letters can be a function depending on what applications are installed on your system and what functions are defined in the script, so the list can never be complete. However, Bash's syntax is simply too complex for Prism to reliably detect functions, so we have to approximate.

> * `npm install abc` treats both `npm` and `install` as functions.

The syntax of command arguments are always specific to the command. In order to fix this, Prism would have to know the syntax of the `npm` command. This is simply too difficult to pull off using regexes. It also doesn't scale. I'm sure there are a bunch of other commands with the same problem.

> or some way to replace the list of functions entirely

We already have that:

```js
Prism.languages.bash.function.pattern = /(^|[\s;|&]|[<>]\()(?:your|list|of|functions)(?=$|[)\s;|&])/;
```

Any regex within a language can be overwritten. The only downside to this approach is that you have to lock down your Prism version. We only guarantee that all grammars follow [this type](https://prismjs.com/docs/global.html#Grammar), but we do not guarantee anything else. So token names, order, regexes, and the general structure of a language can (but rarely do) change from version to version.

---

Since we already have a way to replace tokens, and we can't really do anything about using an approximation to detect functions, I'll now close this issue.

**Closed by RunDevelopment** 2022-03-02 11:23 UTC
Labels: enhancement

**Comment by dhruvkb** [comment] 2022-03-02 12:41
```js
Prism.languages.bash.function.pattern = /.../
```
is almost exactly what I needed, thanks!
