### ISSUE TITLE
Add support for mathematica / wolfram language

### ISSUE THREAD

**Issue by msollami** [PrismJS/prism#2917] opened 2021-05-24 22:17 UTC
**Motivation**
This would be a nice addition to the list of supported languages

**Description**
Added syntax highlighting for mathematica

**Alternatives**
None known alternatives at present, but this project is related: https://github.com/halirutan/WolframLanguage-Google-Prettify

**Comment by RunDevelopment** [comment] 2021-05-25 09:49
Duplicate of #1647

**Closed by RunDevelopment** 2021-05-25 09:49 UTC
Labels: enhancement
