### ISSUE TITLE
Empty line inside code block garbles the output

### ISSUE THREAD

**Issue by ruslaniv** [PrismJS/prism#3096] opened 2021-09-26 11:24 UTC
**Information:**
- Prism version: latest from the website
- Plugins: 
line-highlight
line-numbers
autolinker
show-language
previewers
normalize-whitespace
toolbar
copy-to-clipboard

- Environment: Built in browser in DevonThink 3.7.2

**Description**

If I add an empty line inside a code block then the output text gets garbled. It is still readable but it is shifted downward and line numbers are out of place. The screenshot shows the exact behavior. 
If I remove an empty line or put a character in it, then the code is rendered as it is supposed to.

**Example**

1. Code block with an empty line

```
<pre class="language-python line-numbers"><code>
def quality(total_bill,tip):
    if tip/total_bill  > 0.25:
        return "Generous"

    else:
        return "Other"
</code></pre>
```

That is how it is rendered
![Screen Shot 2021-09-26 at 18 19 23](https://user-images.githubusercontent.com/7631314/134805501-87b57634-7021-4093-a038-621a2385157e.png)

2. Code block without an empty line

```
<pre class="language-python line-numbers"><code>
def quality(total_bill,tip):
    if tip/total_bill  > 0.25:
        return "Generous"
#
    else:
        return "Other"
</code></pre>
```
Screenshot
![Screen Shot 2021-09-26 at 18 20 56](https://user-images.githubusercontent.com/7631314/134805548-c4c316ec-f122-4b68-ae3d-069e3d52d1e6.png)

**Comment by RunDevelopment** [comment] 2021-09-30 08:58
Hello @ruslaniv. Sorry for the delay.

Here is a screenshot of me just inserting your HTML into the [Line numbers](https://prismjs.com/plugins/line-numbers/) plugin page (+ your other plugins + Python) on Chrome:

![image](https://user-images.githubusercontent.com/20878432/135419982-3d941fb1-5ea7-4360-b868-bfddb02e00d6.png)

As you can see, everything works as expected.

From your screenshot, we can also see that the closing tags `</code></pre>` somehow get appended to the code. This is super strange because Prism doesn't do anything that could cause this. It's my first time seeing this.

My guess is that there is something else on your website that causes this problem. Could you please provide a minimal example that reproduces your problem?

You also seem to be using an uncommon browser. Does your problem occur in Safari, Chrome or FireFox as well?

**Comment by RunDevelopment** [comment] 2022-03-02 11:32
I'll close this now due to the lack of information and because there hasn't been a response.

**Closed by RunDevelopment** 2022-03-02 11:32 UTC
Labels: cannot reproduce
